### Direktben megszólítjuk a OpenAI-t
POST https://api.openai.com/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-5-nano",
  "messages": [
    {
      "role": "user",
      "content": "Mi az a Java! Válaszolj egy mondatban!"
    }
  ]
}

### Kérdés a saját alkalmazáshoz
POST http://localhost:8080/api/ask

Mi az a Java?

### Kérdés a saját alkalmazáshoz
POST http://localhost:8080/api/ask

Tudsz internetről adatokat betölteni?

### Java verziók
POST http://localhost:8080/api/java-versions

### Template
POST http://localhost:8080/api/java-classes
Content-Type: application/json

{
  "className": "Map",
  "javaVersion": "21"
}

### Thymeleaf template
POST http://localhost:8080/api/java-keywords
Content-Type: application/json

[
    "private", "public"
]