### Direktben megszólítjuk a OpenAI-t
POST https://api.openai.com/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-5-nano",
  "messages": [
    {
      "role": "user",
      "content": "Mi az a Java! Válaszolj egy mondatban!"
    }
  ]
}

### Kérdés a saját alkalmazáshoz
POST http://localhost:8080/api/ask

Mi az a Java?

### Kérdés a saját alkalmazáshoz
POST http://localhost:8080/api/ask

Tudsz internetről adatokat betölteni?

### Java verziók
POST http://localhost:8080/api/java-versions

### Template
POST http://localhost:8080/api/java-classes
Content-Type: application/json

{
  "className": "Map",
  "javaVersion": "21"
}

### Thymeleaf template
POST http://localhost:8080/api/java-keywords
Content-Type: application/json

[
    "private", "public"
]

### Chat memory - első kérdés
POST http://localhost:8080/api/memory
Content-Type: application/json

{
   "question": "Véletlenszerűen válassz ki egy LLM AI modellt, és írd le csak a nevét!"
}

### Chat memory - második kérdés
POST http://localhost:8080/api/memory
Content-Type: application/json

{
  "id": "1241b9ba-6c6b-4d6d-a119-674f94be6893",
  "question": "A választott modellnek írd le egy mondatban a fő jellemzőit!"
}

### Multimodalis kérdés
POST http://localhost:8080/api/images
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="question"

A megadott kép egy Spring Boot tanulási útvonalat tartalmaz.
Alaposan elemezd a képet, és sorold fel azokat a részeket,
amelyek a Testing témakörhöz kapcsolódnak! Csak az ábrán
szereplő szavak közül válogass!

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="roadmap.png"

< ./roadmap.png

--WebAppBoundary--